[project]
name = "data-service"
version = "0.1.0"
description = "Data service for chatbot system with BigQuery integration"
authors = [
    {name = "rchiarino",email = "rz.chiarino@gmail.com"}
]
readme = "README.md"
requires-python = "^3.9"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
