name: ancap_ia_challenge
services:
  database:
    build: ./database
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend

  data-service:
    build: ./data-service
    ports:
      - 8001:8001
    depends_on:
      - database
    networks:
      - backend
    environment:
      - GCP_PROJECT_ID=ancap-equipo2
      - GCP_DATA_PROJECT_ID=datosancap
      - BIGQUERY_DATASET=entregas_facturacion

  llm-service:
    build: ./llm-service
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - backend
      - frontend
    environment:
      - MCP_SERVER_URI=http://data-service:8001
      - POCKETBASE_URL=http://database:8080
      - LANGSMITH_TRACING=true
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
      - LANGSMITH_PROJECT="chatbot-test"

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge







  
